/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package qux

import org.gradle.api.Project
import org.gradle.api.Plugin
import javax.inject.Inject
import org.gradle.api.component.SoftwareComponentFactory;
import org.gradle.api.tasks.bundling.Zip
import org.gradle.api.attributes.Attribute

public class QuxPlugin implements Plugin<Project> {

  private final SoftwareComponentFactory softwareComponentFactory

  @Inject
  QuxPlugin(SoftwareComponentFactory softwareComponentFactory) {
    this.softwareComponentFactory = softwareComponentFactory
  }

  public void apply(Project project) {
    def adhocComponent = this.softwareComponentFactory.adhoc("quxComponent")

    project.components.add(adhocComponent)

    def distZip = project.file("${project.buildDir}/dist.zip")

    project.configurations {
      "default" {
        canBeConsumed = true
        canBeResolved = true
        attributes {
          // Dummy attribute since gradle requires that we define at least one
          attribute(Attribute.of("my.attribute.name", String), "my-value")
        }
      }
    }

    project.tasks.register("assembleZip", Zip) {
      from project.file("${project.projectDir}/src")
      archiveName = distZip.name
      destinationDir distZip.parentFile
    }

    project.artifacts {
      "default"(distZip) {
        builtBy(project.tasks.named('assembleZip'))
      }
    }

    adhocComponent.addVariantsFromConfiguration(project.configurations.default) {
      it.mapToMavenScope("runtime")
    }
  }
}
